export const SET_PAGE = 'SET_PAGE';

export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';

export const REQUEST_AUTH = 'REQUEST_AUTH';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SET_DOMAIN_DATA = 'SET_DOMAIN_DATA';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

// USERS

export const CREATE_USER_REQUEST = 'user/CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'user/CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'user/CREATE_USER_FAILURE';

export const GET_USER_REQUEST = 'user/GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'user/GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'user/GET_USER_FAILURE';

export const REMOVE_USER_REQUEST = 'user/REMOVE_USER_REQUEST';
export const REMOVE_USER_SUCCESS = 'user/REMOVE_USER_SUCCESS';
export const REMOVE_USER_FAILURE = 'user/REMOVE_USER_FAILURE';

export const LOAD_USERS_REQUEST = 'user/LOAD_USERS_REQUEST';
export const LOAD_USERS_SUCCESS = 'user/LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILURE = 'user/LOAD_USERS_FAILURE';

export const UPDATE_USER_REQUEST = 'user/UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'user/UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'user/UPDATE_USER_FAILURE';

export const SET_USER_DATA = 'user/SET_USER_DATA';


// POLLS

export const SET_POLL_DATA = 'poll/SET_POLL_DATA';
export const RESET_POLL_DATA = 'poll/RESET_POLL_DATA';
export const ADD_POLL_ANSWER = 'poll/ADD_POLL_ANSWER';
export const SET_CORRECT_ANSWER = 'poll/SET_CORRECT_ANSWER';

export const CREATE_POLL_REQUEST = 'poll/CREATE_POLL_REQUEST';
export const CREATE_POLL_SUCCESS = 'poll/CREATE_POLL_SUCCESS';
export const CREATE_POLL_FAILURE = 'poll/CREATE_POLL_FAILURE';

export const REMOVE_POLL_REQUEST = 'poll/REMOVE_POLL_REQUEST';
export const REMOVE_POLL_SUCCESS = 'poll/REMOVE_POLL_SUCCESS';
export const REMOVE_POLL_FAILURE = 'poll/REMOVE_POLL_FAILURE';

export const UPDATE_POLL_REQUEST = 'poll/UPDATE_POLL_REQUEST';
export const UPDATE_POLL_SUCCESS = 'poll/UPDATE_POLL_SUCCESS';
export const UPDATE_POLL_FAILURE = 'poll/UPDATE_POLL_FAILURE';

export const LOAD_POLLS_REQUEST = 'poll/LOAD_POLLS_REQUEST';
export const LOAD_POLLS_SUCCESS = 'poll/LOADPOLLS_SUCCESS';
export const LOAD_POLLS_FAILURE = 'poll/LOAD_POLLS_FAILURE';
