export const languages = {
  aa: 'Afar',
  ab: 'Abkhazian',
  ae: 'Avestan',
  af: 'Afrikaans',
  ak: 'Akan',
  am: 'Amharic',
  an: 'Aragonese',
  ar: 'Arabic',
  as: 'Assamese',
  sq: 'Albanian',
  av: 'Avaric',
  hy: 'Armenian',
  ay: 'Aymara',
  az: 'Azerbaijani',
  ba: 'Bashkir',
  be: 'Belarusian',
  bg: 'Bulgarian',
  bh: 'Bihari languages',
  bi: 'Bislama',
  bm: 'Bambara',
  bn: 'Bengali',
  eu: 'Basque',
  br: 'Breton',
  my: 'Burmese',
  bs: 'Bosnian',
  kw: 'Cornish',
  ca: 'Catalan, Valencian',
  ce: 'Chechen',
  ch: 'Chamorro',
  co: 'Corsican',
  cr: 'Cree',
  km: 'Central Khmer',
  cs: 'Czech',
  cu: 'Church Slavic, Church Slavonic, Old Church Slavonic, Old Slavonic, Old Bulgarian',
  cv: 'Chuvash',
  da: 'Danish',
  dv: 'Divehi, Dhivehi, Maldivian',
  nl: 'Dutch, Flemish',
  dz: 'Dzongkha',
  en: 'English',
  eo: 'Esperanto',
  et: 'Estonian',
  ff: 'Fulah',
  fi: 'Finnish',
  fj: 'Fijian',
  fo: 'Faroese',
  fr: 'French',
  de: 'German',
  gd: 'Gaelic, Scottish Gaelic',
  gl: 'Galician',
  gn: 'Guaraní',
  gu: 'Gujarati',
  ka: 'Georgian',
  hr: 'Croatian',
  ht: 'Haitian, Haitian Creole',
  hu: 'Hungarian',
  hz: 'Herero',
  ia: 'Interlingua',
  id: 'Indonesian',
  ie: 'Interlingue',
  ig: 'Igbo',
  ik: 'Inupiaq',
  io: 'Ido',
  ga: 'Irish',
  is: 'Icelandic',
  it: 'Italian',
  iu: 'Inuktitut',
  ja: 'Japanese',
  jv: 'Javanese',
  kg: 'Kongo',
  ki: 'Kikuyu, Gikuyu',
  kj: 'Kuanyama, Kwanyama',
  kk: 'Kazakh',
  kl: 'Kalaallisut, Greenlandic',
  kn: 'Kannada',
  ko: 'Korean',
  kr: 'Kanuri',
  ks: 'Kashmiri',
  ku: 'Kurdish',
  kv: 'Komi',
  ky: 'Kirghiz, Kyrgyz',
  la: 'Latin',
  lb: 'Luxembourgish, Letzeburgesch',
  li: 'Limburgan, Limburger, Limburgish',
  ln: 'Lingala',
  lo: 'Lao',
  lt: 'Lithuanian',
  lu: 'Luba-Katanga',
  lv: 'Latvian',
  mg: 'Malagasy',
  mh: 'Marshallese',
  mi: 'Maori',
  mk: 'Macedonian',
  ml: 'Malayalam',
  mn: 'Mongolian',
  mr: 'Marathi',
  ms: 'Malay',
  mt: 'Maltese',
  na: 'Nauru',
  nb: 'Norwegian Bokmål',
  nd: 'North Ndebele',
  ne: 'Nepali',
  ng: 'Ndonga',
  nn: 'Norwegian Nynorsk',
  no: 'Norwegian',
  se: 'Northern Sami',
  nv: 'Navajo, Navaho',
  oc: 'Occitan',
  oj: 'Ojibwa',
  om: 'Oromo',
  qu: 'Quechua',
  or: 'Oriya',
  os: 'Ossetian, Ossetic',
  pa: 'Panjabi, Punjabi',
  fa: 'Persian',
  pi: 'Pali',
  pl: 'Polish',
  ps: 'Pashto, Pushto',
  pt: 'Portuguese',
  rm: 'Romansh',
  rn: 'Rundi',
  ro: 'Romanian, Moldavian, Moldovan',
  ru: 'Russian',
  rw: 'Kinyarwanda',
  sa: 'Sanskrit',
  sc: 'Sardinian',
  sd: 'Sindhi',
  es: 'Spanish, Castilian',
  si: 'Sinhala, Sinhalese',
  sk: 'Slovak',
  sl: 'Slovene',
  sm: 'Samoan',
  sn: 'Shona',
  so: 'Somali',
  sr: 'Serbian',
  ss: 'Swati',
  st: 'Southern Sotho',
  su: 'Sundanese',
  sv: 'Swedish',
  sw: 'Swahili',
  ta: 'Tamil',
  te: 'Telugu',
  tg: 'Tajik',
  th: 'Thai',
  ti: 'Tigrinya',
  tk: 'Turkmen',
  tl: 'Tagalog',
  tn: 'Tswana',
  to: 'Tongan (Tonga Islands)',
  tr: 'Turkish',
  ts: 'Tsonga',
  tt: 'Tatar',
  tw: 'Twi',
  ty: 'Tahitian',
  ug: 'Uighur, Uyghur',
  uk: 'Ukrainian',
  ur: 'Urdu',
  uz: 'Uzbek',
  ve: 'Venda',
  vi: 'Vietnamese',
  vo: 'Volapük',
  wa: 'Walloon',
  wo: 'Wolof',
  xh: 'Xhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  za: 'Zhuang, Chuang',
  zh: 'Chinese',
  zu: 'Zulu',
};
